redis:
  uri: "redis://localhost:6379?db=0"

report:
  message: "&9[Report] &r%target% &7reported by &r%reporter%\n     &9Reason: &7%reason%"

messages:
  from: "&7(From: %displayname%&7) %message%"
  to: "&7(To: %displayname%&7) %message%"

polls:
  startMessage: "&8[&eServer&8] &fA poll has just started"
  intervalMessage: "&8[&eServer&8] &fPoll closes in &a60s"
  endMessage: "&8[&eServer&8] &fThe poll has ended. %entry% won!"

slowchat:
  bypass: "compound.slowchat.bypass"
  message: "&cYou may chat again in %seconds% seconds. To bypass this, purcase a rank at &lhello.com"
  seconds: 3

mutechat:
  muted: "&aChat has been muted by %displayname%"
  unmuted: "&cChat has been unmuted by %displayname%"
  bypass: "compound.mutechat.bypass"

gamemode:
  creative: "&aYou have went into Creative mode!"
  survival: "&aYou have went into Survival mode!"

colors:
  primary: "&b"
  secondary: "&f"

waypoints:
  spawn:
    x: 0
    y: 100
    z: 0
    world: "world"
    color: "GREEN"

